### ISSUE TITLE
Support for images in Plio

### ISSUE THREAD

**Issue by dalmia** [avantifellows/plio-frontend#60]
@deepansh96 please feel free to add any details if needed.

**Comment by dalmia** [comment]
Fixed by #62

**Comment by pritamps** [comment]
Hey -- this is not fixed. We have CMS problem support, but not image support. For orgs to be able to use CMS, we will have to give access to CMS to them (which involves licensing and all that nonsense for ALC).

Like -- what Garima asked, about uploading images. We will have to see if giving access to CMS to them is an option. 

Or even, the best option would be opening CMS up, but that has many challenges also... so I wouldn't say this is done, yet. 

Does that make sense? If you feel like CMS support is enough for now, feel free to close again!

**Comment by dalmia** [comment]
Oh, is the access to CMS not already open? I saw a `Sign Up` option on the CMS login page and thought that it was open for everyone. Isliye I marked it as close. Can you please confirm that?

**Comment by dalmia** [comment]
If it is not open for everyone, then, yes, we'll need to figure out something and this is not closed yet.

**Comment by pritamps** [comment]
No no. That's the LMS where you see sign-up. That gives you access as a student. CMS support needs an admin to add you.

**Comment by dalmia** [comment]
Oh, that is a problem then. Let's have a short call tomorrow to discuss this.

**Comment by deepansh96** [comment]
As discussed in the meeting, closing this.
Context - For now, we will specifically create user ids on CMS for the orgs who want to use image/latex support in questions.
